#!/usr/bin/env bash

set -euo pipefail


read -r -p "Old NeoVim configuration files will be deleted. Are you sure you want to proceed? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
    echo "Removing old configuration files..."
    echo "WARN: Old configuration files will be deleted!"
    rm -rf "$HOME/.config/nvim"
    rm -rf "$HOME/.cache/nvim"
    rm -rf "$HOME/.local/share/nvim"
    rm -rf "$HOME/.local/state/nvim"
    echo "Cloning repository..."
    git clone https://github.com/danlikestocode/embervim 
    echo "Copying new configuration files..."
    mv "./embervim/nvim" "$HOME/.config"
    echo "Cleaning...."
    rm -rf "./embervim"
    echo "Finished!"
else
    echo "Stopped installation!"
fi

exit 0





