return {
	-- "zbirenbaum/copilot.lua",
	-- cmd = "Copilot",
	-- event = "InsertEnter",
	-- config = function()
	-- 	require("copilot").setup({
	-- 		panel = {
	-- 			enabled = true,
	-- 			auto_refresh = true,
	-- 			keymap = {
	-- 				jump_prev = "<C-Left>",
	-- 				jump_next = "<C-Right>",
	-- 				accept = "<Right>",
	-- 				refresh = "<Left>",
	-- 				open = "<C-g>",
	-- 			},
	-- 			layout = {
	-- 				position = "bottom", -- | top | left | right
	-- 				ratio = 0.4,
	-- 			},
	-- 		},
	-- 		suggestion = {
	-- 			enabled = true,
	-- 			auto_trigger = true,
	-- 			debounce = 75,
	-- 			keymap = {
	-- 				accept = "<Right>",
	-- 				accept_word = false,
	-- 				accept_line = false,
	-- 				next = "<C-Right>",
	-- 				prev = "<C-Left>",
	-- 				dismiss = "<Left>",
	-- 			},
	-- 		},
	-- 		filetypes = {
	-- 			yaml = false,
	-- 			markdown = false,
	-- 			help = false,
	-- 			gitcommit = false,
	-- 			gitrebase = false,
	-- 			hgcommit = false,
	-- 			svn = false,
	-- 			cvs = false,
	-- 			["."] = false,
	-- 		},
	-- 		copilot_node_command = "node", -- Node.js version must be > 18.x
	-- 		server_opts_overrides = {},
	-- 	})
	-- end,
}
