-- EmberVim
-- Author: danlikestocode
-- ---------------------
-- This is the main entry point for any neovim configuration, it is just
-- requiring the file located in lua/embervim/init.lua
--
-- To install additional plugins, you can add them to the plugins.lua file
-- located in lua/embervim/plugins.lua
--
-- To add custom keybinds, you can add them to the keybinds.lua file
-- located in lua/embervim/keybinds.lua
--
-- To add custom settings, you can add them to the set.lua file
-- located in lua/embervim/set.lua
--
-- To configure specific plugins, you can add said lua file to after/plugin

require("embervim")

--  ,,
-- `""*$b..
--      ""*$o.
--          "$$o.
--            "*$$o.
--               "$$$o.
--                 "$$$$bo...       ..o:
--                   "$$$$$$$$booocS$$$    ..    ,.
--                ".    "*$$$$SP     V$o..o$$. .$$$b
--                 "$$o. .$$$$$o. ...A$$$$$$$$$$$$$$b
--           ""bo.   "*$$$$$$$$$$$$$$$$$$$$P*$$$$$$$$:
--              "$$.    V$$$$$$$$$P"**""*"'   VP  * "l
--                "$$$o.4$$$$$$$$X
--                 "*$$$$$$$$$$$$$AoA$o..oooooo..           .b
--                        .X$$$$$$$$$$$P""     ""*oo,,     ,$P
--                       $$P""V$$$$$$$:    .        ""*****"
--                     .*"    A$$$$$$$$o.4;      .
--                          .oP""   "$$$$$$b.  .$;
--                                   A$$$$$$$$$$P
--                                   "  "$$$$$P"
--                                       $$P*"
--                                      .$"
--                                      "
